-- Short notes:
-- in android we can take advertising ID, if we will have ios version of the app in future IOS has similar ID
-- we can store information about the device its self like manufacture, OS, OS Version etc
-- We will store our refresh token in a cookie HTTPOnly cookie

CREATE TABLE IF NOT EXISTS sessions(
    user_id UUID REFERENCES users,
    device_id TEXT NOT NULL, --(VALUE GENERATED BY device)
    refresh_token VARCHAR NOT NULL ,
    expires_at INTEGER NOT NULL ,
    PRIMARY KEY (user_id, device_id)
);

ALTER TABLE sessions ADD CONSTRAINT "current_sessions_uiq" UNIQUE (user_id, device_id);
ALTER TABLE sessions ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT (now());
ALTER TABLE sessions ADD COLUMN  deleted_at TIMESTAMPTZ NOT NULL DEFAULT '0001-01-01 00:00:00Z';
